.TH "GIT\-SUBMIT" "1" "09/22/2015" "Git extension" "Gerrit Tools"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
git-submit \- Submit commit(s) for Gerrit code review
.SH "SYNOPSIS"
.sp
.nf
\fIgit submit \fR [\-r | \-\-reviewer REVIEWER] [\-R | \-\-remote REMOTE] [\-n]
.fi
.sp
.SH "DESCRIPTION"
.sp
This command submits committed changed for Gerrit code review\&. It is equivalent to pushing the current branch to the special Gerrit refs/for/[BRANCH]\&.
.sp
The command automatically detects the current branch, and selects the remote branch based on the configuration, unless the remote is explicitely specified on the command line\&. It also allows reviewers to be specified directly\&.
.SH "OPTIONS"
.PP
\-n, \-\-dry\-run
.RS 4
Don\(cqt actually submit the review(s), just show the git command which would be executed\&.
.RE
.PP
\-r, \-\-reviewer REVIEWER
.RS 4
Add a reviewer for the review\&. REVIEWER can be eiher a Gerrit username or an email address\&. Multiple reviers can be added separated by comma, or by repeated use of this option\&.
.RE
.PP
\-R, \-\-remote REMOTE
.RS 4
Push to the specified remote instead of the branch / project default.\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Submit commits for review to default remote, adding "tom" and "jerry" as reviewers:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git submit -r tom,jerry
.fi
.if n \{\
.RE
.\}
.sp
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Submit commits for review to 'origin' remote explicitely, without specifying reviewers.
.sp
.if n \{\
.RS 4
.\}
.nf
$ git submit --remote=origin
.fi
.if n \{\
.RE
.\}
.sp
.SH "SEE ALSO"
.sp
\fBgit-push\fR(1) \fBgit-commit\fR(1)
.SH "GIT"
.sp
Not part of the either the \fBgit\fR(1) suite or \fBgerrit\fR\&.
